"""Armani Middle East Trading - commercial KPI dashboard (Streamlit).

Generated by part3_dashboard_v1.0.ipynb. Reads dashboard_data_v1.0.db (same folder).
Run:  streamlit run dashboard_app_v1.0.py
"""
from __future__ import annotations

import sqlite3
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

VERSION = "v1.0"
DB_PATH = Path(__file__).parent / f"dashboard_data_{VERSION}.db"
WEEKS_PER_YEAR = 52

# validated categorical palette (blue / orange / aqua), neutrals and status colours
BLUE, ORANGE, AQUA, YELLOW = "#2a78d6", "#eb6834", "#1baf7a", "#eda100"
BLUE_LIGHT, AQUA_LIGHT = "#9ec5f4", "#bfe9d9"
INK, INK2, MUTED, GRID, SURFACE = "#0b0b0b", "#52514e", "#8a8984", "#e6e5e1", "#fcfcfb"
STATUS_COLOR = {"High": "#d03b3b", "Medium": "#ec835a", "Low": "#fab219"}
STATUS_ICON = {"High": "▲ High", "Medium": "◆ Medium", "Low": "● Low"}
RATING_COLOR = {"A": "#0ca30c", "B": "#7fb800", "C": "#fab219", "D": "#ec835a", "E": "#d03b3b"}

DEFAULT_THRESHOLDS = {
    "cover_max": 26.0,        # overstock: weeks of cover above this
    "lost_share_max": 20.0,   # stock-out risk: % of forecast revenue not served
    "rev_decline_pct": 10.0,  # revenue decline vs same weeks last year (26 weeks)
    "margin_drop_pp": 1.0,    # gross margin drop in percentage points (13 vs previous 52 weeks)
    "ecl_gp_max": 6.0,        # credit: expected credit loss as % of gross profit
    "dso_max": 55.0,          # credit: DSO in days
    "peak_uplift_pct": 25.0,  # seasonal peak: forecast peak vs last 13 weeks
}

# ----------------------------------------------------------------------------- data
@st.cache_data(show_spinner=False)
def load_data() -> dict:
    con = sqlite3.connect(DB_PATH)
    d = {t: pd.read_sql(f"SELECT * FROM {t}", con) for t in ["hist", "fcst", "products", "credit_defaults", "meta"]}
    con.close()
    for t in ("hist", "fcst"):
        d[t]["week_start"] = pd.to_datetime(d[t]["week_start"])
        yi = (d[t].week_id - 1) // 52 + 1
        q = ((d[t].week_id - 1) % 52) // 13 + 1
        d[t]["pq"] = "Y" + yi.astype(str) + "-Q" + q.astype(str)
    d["meta"] = dict(zip(d["meta"].key, d["meta"].value))
    return d


# ----------------------------------------------------------------------------- formatting
def money(x: float, dec: int = 1) -> str:
    if x is None or not np.isfinite(x):
        return "n/a"
    a = abs(x)
    s = f"{a / 1e9:.{dec}f}B" if a >= 1e9 else f"{a / 1e6:.{dec}f}M" if a >= 1e6 else f"{a / 1e3:.0f}K" if a >= 1e4 else f"{a:,.0f}"
    return ("-" if x < 0 else "") + "$" + s


def pct(x: float, dec: int = 1) -> str:
    return "n/a" if x is None or not np.isfinite(x) else f"{100 * x:.{dec}f}%"


def num(x: float, dec: int = 0) -> str:
    return "n/a" if x is None or not np.isfinite(x) else f"{x:,.{dec}f}"


# ----------------------------------------------------------------------------- KPI logic (pure functions, unit-tested in the notebook)
def kpis(h: pd.DataFrame, a: int, b: int) -> dict:
    """KPIs for weeks a..b (inclusive) of the (already filtered) history frame."""
    s = h[(h.week_id >= a) & (h.week_id <= b)]
    weeks = b - a + 1
    rev, gp, op, cogs, units = s.revenue.sum(), s.gross_profit.sum(), s.operating_profit.sum(), s.cogs.sum(), s.units.sum()
    stock_v = s.groupby("week_id").stock_value.sum(min_count=1).dropna()
    stock_u = s.groupby("week_id").stock_units.sum(min_count=1).dropna()
    avg_stock = stock_v.mean() if len(stock_v) else np.nan
    dem = s.demand_est.sum()
    return {
        "weeks": weeks, "revenue": rev, "gross_profit": gp, "operating_profit": op, "cogs": cogs, "units": units, "demand": dem,
        "gpm": gp / rev if rev else np.nan, "opm": op / rev if rev else np.nan, "opex": gp - op,
        "avg_stock_value": avg_stock,
        "turnover": (cogs * WEEKS_PER_YEAR / weeks) / avg_stock if avg_stock and avg_stock > 0 else np.nan,
        "dsi": avg_stock / (cogs / (weeks * 7)) if cogs > 0 and avg_stock == avg_stock else np.nan,
        "weeks_cover": (stock_u.mean() / (dem / weeks)) if len(stock_u) and dem > 0 else np.nan,
        "service_level": units / dem if dem else np.nan,
        "lost_revenue": s.lost_revenue.sum(), "lost_units": s.lost_units.sum(),
        "lost_share": s.lost_revenue.sum() / (rev + s.lost_revenue.sum()) if rev else np.nan,
    }


def growth_yoy(h: pd.DataFrame, a: int, b: int) -> float:
    """Revenue growth of weeks a..b versus the same weeks 52 weeks earlier."""
    if a - WEEKS_PER_YEAR < 1:
        return np.nan
    cur = h[(h.week_id >= a) & (h.week_id <= b)].revenue.sum()
    prev = h[(h.week_id >= a - WEEKS_PER_YEAR) & (h.week_id <= b - WEEKS_PER_YEAR)].revenue.sum()
    return cur / prev - 1 if prev else np.nan


def credit_table(h: pd.DataFrame, a: int, b: int, cred: pd.DataFrame) -> pd.DataFrame:
    """ASSUMPTION-BASED credit scenario: DSO, receivables, expected loss and a transparent A-E rating per category."""
    s = h[(h.week_id >= a) & (h.week_id <= b)]
    weeks = b - a + 1
    g = s.groupby("category").agg(revenue=("revenue", "sum"), gross_profit=("gross_profit", "sum")).reset_index()
    g = g.merge(cred, on="category", how="left")
    share, dflt = g.credit_share_pct / 100, g.annual_default_rate_pct / 100
    g["dso"] = share * (g.terms_days + g.avg_delay_days)
    g["receivables"] = g.revenue / (weeks * 7) * g.dso
    g["ecl_annual"] = share * dflt * g.revenue * WEEKS_PER_YEAR / weeks
    g["ecl_pct_gp"] = g.ecl_annual / (g.gross_profit * WEEKS_PER_YEAR / weeks).replace(0, np.nan)
    g["rev_share"] = g.revenue / g.revenue.sum()
    g["s_default"] = np.minimum(dflt / 0.03, 1) * 100
    g["s_late"] = np.minimum(g.avg_delay_days / g.terms_days / 0.5, 1) * 100
    g["s_buffer"] = np.minimum(g.ecl_pct_gp / 0.15, 1) * 100
    g["s_conc"] = np.minimum(g.rev_share / 0.25, 1) * 100
    g["risk_score"] = 0.40 * g.s_default + 0.20 * g.s_late + 0.25 * g.s_buffer + 0.15 * g.s_conc
    g["rating"] = pd.cut(g.risk_score, [-1, 20, 35, 50, 65, 1000], labels=list("ABCDE"), right=False).astype(str)
    return g


def compute_alerts(d: dict, cred: pd.DataFrame, thr: dict) -> pd.DataFrame:
    """Rule-based alerts (company-wide, independent of the sidebar filters). $ at stake is in the units named in 'at_stake_basis'."""
    h, f, prods = d["hist"], d["fcst"], d["products"]
    last = int(h.week_id.max())
    rows = []

    def add(sev, typ, scope, name, metric, value, threshold, stake, basis, action, kind="data"):
        rows.append(dict(severity=sev, type=typ, scope=scope, name=name, metric=metric, value=value, threshold=threshold,
                         at_stake=stake, at_stake_basis=basis, action=action, kind=kind))

    cur13 = h[h.week_id > last - 13]
    cur26 = h[h.week_id > last - 26]
    for pid, g in cur13.groupby("product_id"):
        name = g.product_name.iloc[0]
        dem_w, stock_w = g.demand_est.mean(), g.stock_units.mean()
        cover = stock_w / dem_w if dem_w else np.nan
        if cover == cover and cover > thr["cover_max"]:
            excess = (stock_w - thr["cover_max"] * dem_w)
            add("High" if cover > 4 * thr["cover_max"] else "Medium", "Overstock", "Product", name, "weeks of cover", cover, thr["cover_max"],
                excess * g.unit_cogs.iloc[-1], "capital tied up (at cost)",
                f"Pause purchasing for ~{(stock_w - thr['cover_max'] * dem_w) / dem_w:,.0f} weeks; excess stock ~{excess:,.0f} units - promote or liquidate.")
    for pid, g in f.groupby("product_id"):
        rev, lost = g.exp_revenue.sum(), g.exp_lost_revenue.sum()
        share = lost / rev if rev else 0
        if share * 100 > thr["lost_share_max"]:
            hs = h[(h.product_id == pid) & (h.week_id > last - 52)]
            p90_peak = g.sort_values("h").head(8).p90.max()
            add("High" if share > 0.5 else "Medium", "Stock-out risk", "Product", g.product_name.iloc[0], "% of forecast demand revenue not served", 100 * share,
                thr["lost_share_max"], lost, "revenue at risk (next 26 weeks)",
                f"Raise stock cover: plan for >= {p90_peak:,.0f} units/week in the next 8 weeks (P90); typical stock last year {hs.stock_units.median():,.0f} units.")
    prev26 = h[(h.week_id <= last - 26) & (h.week_id > last - 78)]
    for pid, g in cur26.groupby("product_id"):
        year_ago = h[(h.product_id == pid) & (h.week_id > last - 26 - 52) & (h.week_id <= last - 52)].revenue.sum()
        if year_ago > 0:
            ch = g.revenue.sum() / year_ago - 1
            if ch * 100 < -thr["rev_decline_pct"]:
                add("Medium", "Revenue decline", "Product", g.product_name.iloc[0], "revenue vs same weeks last year (%)", 100 * ch, -thr["rev_decline_pct"],
                    year_ago - g.revenue.sum(), "revenue shortfall (26 weeks)", "Check stock availability and demand drivers for this product.")
    base = h[(h.week_id <= last - 13) & (h.week_id > last - 65)]
    for pid, g in cur13.groupby("product_id"):
        b = base[base.product_id == pid]
        if len(b) and g.revenue.sum() > 0 and b.revenue.sum() > 0:
            drop = 100 * (b.gross_profit.sum() / b.revenue.sum() - g.gross_profit.sum() / g.revenue.sum())
            if drop > thr["margin_drop_pp"]:
                add("Medium", "Margin erosion", "Product", g.product_name.iloc[0], "gross margin drop (pp)", drop, thr["margin_drop_pp"],
                    g.revenue.sum() * drop / 100, "gross profit lost (13 weeks)", "Review price vs landed cost; COGS increased faster than price.")
    ct = credit_table(h, last - 51, last, cred)
    for r in ct.itertuples():
        if r.ecl_pct_gp * 100 > thr["ecl_gp_max"] or r.dso > thr["dso_max"]:
            sev = "High" if r.rating in ("D", "E") else "Medium"
            add(sev, "Credit exposure (scenario)", "Category", r.category, f"DSO {r.dso:.0f} d | expected loss {100 * r.ecl_pct_gp:.1f}% of GP",
                r.ecl_pct_gp * 100, thr["ecl_gp_max"], r.ecl_annual, "expected credit loss / year", "Tighten terms, require credit insurance, focus collections.", kind="scenario")
    fw = f.groupby("week_id").agg(p50=("demand_forecast", "sum"))
    recent = cur13.groupby("week_id").demand_est.sum().mean()
    pk = fw.p50.max() / recent - 1
    if pk * 100 > thr["peak_uplift_pct"]:
        add("Low", "Seasonal peak ahead", "Company", "All products", "forecast peak vs last 13 weeks (%)", 100 * pk, thr["peak_uplift_pct"], 0.0, "-",
            f"Demand peaks in week {int(fw.p50.idxmax())} (+{100 * pk:.0f}% vs recent weeks): pre-build stock and confirm logistics capacity.")
    out = pd.DataFrame(rows)
    if out.empty:
        return pd.DataFrame(columns=["severity", "type", "scope", "name", "metric", "value", "threshold", "at_stake", "at_stake_basis", "action", "kind"])
    out["_o"] = out.severity.map({"High": 0, "Medium": 1, "Low": 2})
    return out.sort_values(["_o", "at_stake"], ascending=[True, False]).drop(columns="_o").reset_index(drop=True)


# ----------------------------------------------------------------------------- chart helpers
def style(fig: go.Figure, height: int = 360, title: str | None = None, legend: bool = True) -> go.Figure:
    fig.update_layout(
        height=height, margin=dict(l=8, r=8, t=36 if legend else 8, b=8), paper_bgcolor=SURFACE, plot_bgcolor=SURFACE, meta=title,
        font=dict(color=INK2, size=12),
        legend=dict(orientation="h", y=1.0, yanchor="bottom", x=0, bgcolor="rgba(0,0,0,0)") if legend else dict(visible=False), hovermode="x unified")
    fig.update_xaxes(showgrid=False, linecolor=GRID, zeroline=False)
    fig.update_yaxes(gridcolor=GRID, zeroline=False)
    return fig


def show(fig: go.Figure, key: str) -> None:
    if fig.layout.meta:
        st.markdown(f"**{fig.layout.meta}**")
    st.plotly_chart(fig, width="stretch", key=key, config={"displaylogo": False})


def sev_html(sev: str) -> str:
    return f"<span style='color:{STATUS_COLOR[sev]};font-weight:600'>{STATUS_ICON[sev]}</span>"


# ----------------------------------------------------------------------------- UI pieces
def alerts_table(al: pd.DataFrame, n: int | None = None, key: str = "al", compact: bool = False) -> None:
    if al.empty:
        st.success("No alerts at the current thresholds.")
        return
    t = al.head(n) if n else al
    t = t.assign(severity=t.severity.map(STATUS_ICON), kind=t.kind.map({"data": "data", "scenario": "scenario (assumptions)"}))
    cols = ["severity", "type", "name", "at_stake"] if compact else ["severity", "type", "name", "value", "threshold", "at_stake", "at_stake_basis", "action"]
    st.dataframe(t[cols], hide_index=True, width="stretch", key=key,
                 column_config={"severity": "Severity", "type": "Alert", "name": "Where", "metric": "Metric", "value": st.column_config.NumberColumn("Value", format="%.1f"),
                                "threshold": st.column_config.NumberColumn("Threshold", format="%.1f"),
                                "at_stake": st.column_config.NumberColumn("$ at stake", format="compact"), "at_stake_basis": "Basis",
                                "action": st.column_config.TextColumn("Recommended action", width="large"), "kind": "Source"})


def kpi_cards(k: dict, kp: dict | None, g: float, ct: pd.DataFrame, a: int, b: int) -> None:
    def d_pp(x, y):
        return None if kp is None or not (np.isfinite(x) and np.isfinite(y)) else f"{100 * (x - y):+.1f} pp"

    def d_rel(x, y):
        return None if kp is None or not (np.isfinite(x) and np.isfinite(y) and y) else f"{100 * (x / y - 1):+.1f}%"

    c = st.columns(4)
    c[0].metric("Revenue", money(k["revenue"]), None if g != g else f"{100 * g:+.1f}% vs last year", help="Sum of weekly sales x price in the selected period. Delta = same weeks one year earlier.")
    c[1].metric("Gross profit margin", pct(k["gpm"]), d_pp(k["gpm"], kp["gpm"]) if kp else None, help="Gross profit / revenue (sums, not averages of ratios).")
    c[2].metric("Operating profit", money(k["operating_profit"]), d_rel(k["operating_profit"], kp["operating_profit"]) if kp else None,
                help=f"Operating margin {pct(k['opm'])}. Operating expenses are not in the data; implied opex = gross profit - operating profit = {money(k['opex'])}.")
    c[3].metric("Service level (fill rate)", pct(k["service_level"]), d_pp(k["service_level"], kp["service_level"]) if kp else None,
                help="Units sold / reconstructed demand. The gap is demand lost to stock-outs and stock caps.")
    c = st.columns(4)
    c[0].metric("Inventory turnover (x / year)", num(k["turnover"], 1), d_rel(k["turnover"], kp["turnover"]) if kp else None,
                help="Annualised COGS / average inventory at cost (stock available during each week).")
    c[1].metric("Days sales of inventory (DSI)", f"{num(k['dsi'], 0)} days", d_rel(k["dsi"], kp["dsi"]) if kp else None, delta_color="inverse",
                help="Average inventory at cost / COGS per day. Lower is leaner.")
    dso = float((ct.dso * ct.revenue).sum() / ct.revenue.sum()) if len(ct) else np.nan
    c[2].metric("DSO - scenario", f"{num(dso, 0)} days", help="ASSUMPTION-BASED: the data has no receivables. DSO = credit share x (payment terms + average delay), revenue-weighted. Edit assumptions in the Sales & Credit tab.")
    worst = ct.sort_values("risk_score", ascending=False).head(1)
    c[3].metric("Default risk rating - scenario", worst.rating.iloc[0] if len(worst) else "n/a", f"worst: {worst.category.iloc[0]}" if len(worst) else None, delta_color="off",
                help="ASSUMPTION-BASED A-E rating (A lowest risk) from assumed default rate, lateness, loss vs margin and revenue concentration.")


# ----------------------------------------------------------------------------- tabs
def tab_exec(d, h, f, cred, a, b, label, al):
    k = kpis(h, a, b)
    kp = kpis(h, a - WEEKS_PER_YEAR, b - WEEKS_PER_YEAR) if a - WEEKS_PER_YEAR >= 1 else None
    ct = credit_table(h, a, b, cred)
    kpi_cards(k, kp, growth_yoy(h, a, b), ct, a, b)
    # headline insights
    meta = d["meta"]
    last = int(meta["last_week_id"])
    ly_weeks = range(last - 52 + 1, last - 52 + 27)                       # same 26 weeks one year before the forecast
    fdem = f.demand_forecast.sum()
    ly_dem = h[h.week_id.isin(ly_weeks)].demand_est.sum()
    cur13 = d["hist"][d["hist"].week_id > last - 13]
    pc = cur13.groupby("product_name").agg(stock=("stock_units", "mean"), dem=("demand_est", "mean"), cogs=("unit_cogs", "last"))
    over = pc[pc.stock / pc.dem > DEFAULT_THRESHOLDS["cover_max"]]
    tied = ((over.stock - DEFAULT_THRESHOLDS["cover_max"] * over.dem) * over.cogs).sum()
    st.markdown("##### What the numbers say")
    st.markdown(
        f"- **{pct(k['lost_share'])} of demand went unserved** in {label.lower()}: about **{money(k['lost_revenue'])}** of revenue lost to stock-outs and stock caps "
        f"(service level {pct(k['service_level'])}).\n"
        f"- **{len(over)} products hold more than {DEFAULT_THRESHOLDS['cover_max']:.0f} weeks of stock**, tying up roughly **{money(tied)}** of excess inventory at cost "
        f"while the lean products run out.\n"
        f"- **Next 26 weeks:** forecast demand {num(fdem)} units, {('%+.1f%%' % (100 * (fdem / ly_dem - 1))) if ly_dem else 'n/a'} vs the same weeks last year, "
        f"entering the seasonal peak; at historical stock levels about **{pct(f.exp_lost_revenue.sum() / f.exp_revenue.sum())}** of that demand would again be unserved.\n"
        f"- **Margins are stable** ({pct(k['gpm'])} gross); the opportunity is volume and stock, not price.")
    basis = st.radio("Forecast basis", ["At historical stock levels (comparable to actuals)", "Unconstrained demand potential"], horizontal=True, key="exec_basis")
    c1, c2 = st.columns(2)
    hq = h.groupby("pq").agg(revenue=("revenue", "sum"), gp=("gross_profit", "sum"), op=("operating_profit", "sum"), ws=("week_start", "min")).reset_index().sort_values("ws")
    fq = f.groupby("pq").agg(exp_sales=("exp_sales_revenue", "sum"), pot=("exp_revenue", "sum"), ws=("week_start", "min")).reset_index().sort_values("ws")
    fig = go.Figure()
    fig.add_bar(x=hq.pq, y=hq.revenue, name="Actual revenue", marker_color=BLUE, hovertemplate="%{y:$,.0f}")
    ycol, yname = ("exp_sales", "Forecast revenue (at historical stock)") if basis.startswith("At") else ("pot", "Forecast revenue potential (unconstrained)")
    fig.add_bar(x=fq.pq, y=fq[ycol], name=yname, marker_color=AQUA, hovertemplate="%{y:$,.0f}")
    if basis.startswith("At"):
        fig.add_scatter(x=fq.pq, y=fq.pot, mode="markers", name="Demand potential", marker=dict(color=ORANGE, size=10, line=dict(color=SURFACE, width=2)), hovertemplate="%{y:$,.0f}")
    fig.update_layout(barmode="group", bargap=0.25)
    fig.update_yaxes(tickprefix="$", tickformat="~s")
    with c1:
        show(style(fig, 360, "Revenue by 13-week quarter (Y = data year) and 26-week forecast"), "exec_rev")
    gm = h.groupby("pq").agg(rev=("revenue", "sum"), gp=("gross_profit", "sum"), op=("operating_profit", "sum"), ws=("week_start", "min")).reset_index().sort_values("ws")
    fig = go.Figure()
    fig.add_scatter(x=gm.pq, y=gm.gp / gm.rev, name="Gross margin", mode="lines+markers", line=dict(color=BLUE, width=2), marker=dict(size=7), hovertemplate="%{y:.1%}")
    fig.add_scatter(x=gm.pq, y=gm.op / gm.rev, name="Operating margin", mode="lines+markers", line=dict(color=ORANGE, width=2), marker=dict(size=7), hovertemplate="%{y:.1%}")
    fig.update_yaxes(tickformat=".0%", rangemode="tozero")
    with c2:
        show(style(fig, 360, "Margins by quarter"), "exec_margin")
    c1, c2 = st.columns([3, 2])
    dh = h[h.week_id > b - 104].groupby(["week_id", "week_start"]).agg(sales=("units", "sum"), dem=("demand_est", "sum")).reset_index()
    ff = f.groupby(["week_id", "week_start"]).agg(p50=("demand_forecast", "sum"), p10=("p10", "sum"), p90=("p90", "sum")).reset_index()
    fig = go.Figure()
    fig.add_scatter(x=dh.week_start, y=dh.sales, name="Observed sales", line=dict(color=BLUE, width=2), hovertemplate="%{y:,.0f}")
    fig.add_scatter(x=dh.week_start, y=dh.dem, name="Reconstructed demand", line=dict(color=ORANGE, width=2), hovertemplate="%{y:,.0f}")
    fig.add_scatter(x=ff.week_start, y=ff.p90, line=dict(width=0), showlegend=False, hoverinfo="skip")
    fig.add_scatter(x=ff.week_start, y=ff.p10, line=dict(width=0), fill="tonexty", fillcolor="rgba(27,175,122,0.22)", name="Forecast P10-P90", hoverinfo="skip")
    fig.add_scatter(x=ff.week_start, y=ff.p50, name="Forecast demand (P50)", line=dict(color=AQUA, width=2.5), hovertemplate="%{y:,.0f}")
    fig.update_yaxes(tickformat="~s")
    with c1:
        show(style(fig, 380, "Weekly units, all selected products: observed sales vs demand vs forecast"), "exec_demand")
    with c2:
        st.markdown("##### Top alerts")
        alerts_table(al, 6, key="exec_alerts", compact=True)
        st.caption("Full list and thresholds in the Alerts tab.")


def tab_financial(d, h, f, cred, a, b, label):
    k = kpis(h, a, b)
    grain = st.radio("Granularity", ["13-week quarter", "Calendar month (by week start)"], horizontal=True, key="fin_grain")
    key = "pq" if grain.startswith("13") else "ym"
    g = h.groupby(key).agg(revenue=("revenue", "sum"), gp=("gross_profit", "sum"), op=("operating_profit", "sum"), cogs=("cogs", "sum"), ws=("week_start", "min")).reset_index().sort_values("ws")
    c1, c2 = st.columns(2)
    fig = go.Figure()
    fig.add_bar(x=g[key], y=g.revenue, name="Revenue", marker_color=BLUE, hovertemplate="%{y:$,.0f}")
    fig.add_bar(x=g[key], y=g.gp, name="Gross profit", marker_color=ORANGE, hovertemplate="%{y:$,.0f}")
    fig.add_bar(x=g[key], y=g.op, name="Operating profit", marker_color=AQUA, hovertemplate="%{y:$,.0f}")
    fig.update_layout(barmode="group", bargap=0.2); fig.update_yaxes(tickprefix="$", tickformat="~s")
    with c1:
        show(style(fig, 380, "Revenue, gross profit and operating profit"), "fin_pl")
    per_year = 4 if key == "pq" else 12
    g["yoy"] = g.revenue.pct_change(per_year)
    gy = g.dropna(subset=["yoy"])
    fig = go.Figure(go.Bar(x=gy[key], y=gy.yoy, marker_color=[BLUE if v >= 0 else "#d03b3b" for v in gy.yoy], hovertemplate="%{y:.1%}"))
    fig.update_yaxes(tickformat=".0%")
    with c2:
        show(style(fig, 380, "Revenue growth vs same period last year", legend=False), "fin_yoy")
    c1, c2 = st.columns(2)
    fig = go.Figure(go.Waterfall(x=["Revenue", "COGS", "Gross profit", "Operating expenses (implied)", "Operating profit"], measure=["absolute", "relative", "total", "relative", "total"],
                                 y=[k["revenue"], -k["cogs"], 0, -k["opex"], 0], connector=dict(line=dict(color=GRID)), increasing=dict(marker=dict(color=BLUE)),
                                 decreasing=dict(marker=dict(color=ORANGE)), totals=dict(marker=dict(color=AQUA)), hovertemplate="%{y:$,.0f}"))
    fig.update_yaxes(tickprefix="$", tickformat="~s")
    with c1:
        show(style(fig, 360, f"From revenue to operating profit - {label.lower()}", legend=False), "fin_waterfall")
    gm = g.assign(gpm=g.gp / g.revenue, opm=g.op / g.revenue)
    fig = go.Figure()
    fig.add_scatter(x=gm[key], y=gm.gpm, name="Gross margin", line=dict(color=BLUE, width=2), hovertemplate="%{y:.1%}")
    fig.add_scatter(x=gm[key], y=gm.opm, name="Operating margin", line=dict(color=ORANGE, width=2), hovertemplate="%{y:.1%}")
    fig.update_yaxes(tickformat=".0%", rangemode="tozero")
    with c2:
        show(style(fig, 360, "Margin trend"), "fin_margin")
    rows = []
    for cat, hc in h.groupby("category"):
        kk = kpis(hc, a, b)
        rows.append(dict(category=cat, revenue=kk["revenue"], growth=growth_yoy(hc, a, b), gross_profit=kk["gross_profit"], gpm=kk["gpm"], operating_profit=kk["operating_profit"], opm=kk["opm"]))
    t = pd.DataFrame(rows).sort_values("revenue", ascending=False)
    st.markdown("##### By category")
    st.dataframe(t, hide_index=True, width="stretch", column_config={
        "category": "Category", "revenue": st.column_config.NumberColumn("Revenue ($)", format="compact"), "growth": st.column_config.NumberColumn("Growth vs last year", format="percent"),
        "gross_profit": st.column_config.NumberColumn("Gross profit ($)", format="compact"), "gpm": st.column_config.NumberColumn("Gross margin", format="percent"),
        "operating_profit": st.column_config.NumberColumn("Operating profit ($)", format="compact"), "opm": st.column_config.NumberColumn("Operating margin", format="percent")})


def tab_ops(d, h, f, cred, a, b, label, thr):
    k = kpis(h, a, b)
    c = st.columns(5)
    c[0].metric("Inventory turnover (x/yr)", num(k["turnover"], 1))
    c[1].metric("DSI", f"{num(k['dsi'], 0)} days")
    c[2].metric("Weeks of cover", num(k["weeks_cover"], 1))
    c[3].metric("Service level", pct(k["service_level"]))
    c[4].metric("Revenue lost to stock limits", money(k["lost_revenue"]))
    rows = []
    for pid, hp in h.groupby("product_id"):
        kk = kpis(hp, a, b)
        rows.append(dict(product=hp.product_name.iloc[0], category=hp.category.iloc[0], segment=hp.segment.iloc[0], revenue=kk["revenue"], turnover=kk["turnover"], dsi=kk["dsi"],
                         weeks_cover=kk["weeks_cover"], service_level=kk["service_level"], lost_revenue=kk["lost_revenue"], avg_stock_value=kk["avg_stock_value"]))
    pt = pd.DataFrame(rows)
    c1, c2 = st.columns(2)
    s = pt.sort_values("weeks_cover")
    fig = go.Figure(go.Bar(y=s["product"], x=s.weeks_cover, orientation="h", marker_color=[ORANGE if v > thr["cover_max"] else BLUE for v in s.weeks_cover], hovertemplate="%{x:,.1f} weeks"))
    fig.add_vline(x=thr["cover_max"], line=dict(color=INK2, dash="dash"), annotation_text=f"limit {thr['cover_max']:.0f} wks", annotation_position="top")
    fig.update_xaxes(title="weeks of cover")
    with c1:
        show(style(fig, 640, "Weeks of cover by product (orange = above the overstock limit)", legend=False), "ops_cover")
    lc = h[(h.week_id >= a) & (h.week_id <= b)].groupby("category").agg(lost=("lost_revenue", "sum"), rev=("revenue", "sum")).reset_index().sort_values("lost")
    fig = go.Figure()
    fig.add_bar(y=lc.category, x=lc.rev, orientation="h", name="Revenue achieved", marker_color=BLUE, hovertemplate="%{x:$,.0f}")
    fig.add_bar(y=lc.category, x=lc.lost, orientation="h", name="Revenue lost to stock limits", marker_color=ORANGE, hovertemplate="%{x:$,.0f}")
    fig.update_layout(barmode="stack"); fig.update_xaxes(tickprefix="$", tickformat="~s")
    with c2:
        show(style(fig, 330, "Revenue achieved vs lost, by category"), "ops_lost")
        mm = h.groupby(["pq", "segment"]).lost_revenue.sum().unstack().fillna(0)
        first = h.groupby("pq").week_start.min().sort_values().index
        mm = mm.loc[first]
        fig = go.Figure()
        for seg_, col_, nm in [("normal", BLUE, "23 normal-stock products"), ("high_stock", ORANGE, "7 high-stock products")]:
            if seg_ in mm.columns:
                fig.add_bar(x=mm.index, y=mm[seg_], name=nm, marker_color=col_, hovertemplate="%{y:$,.0f}")
        fig.update_layout(barmode="stack"); fig.update_yaxes(tickprefix="$", tickformat="~s")
        show(style(fig, 300, "Lost revenue by quarter and stock segment"), "ops_lost_q")
    st.markdown("##### Product inventory KPIs")
    st.dataframe(pt.sort_values("weeks_cover", ascending=False), hide_index=True, width="stretch", column_config={
        "product": "Product", "category": "Category", "segment": "Segment", "revenue": st.column_config.NumberColumn("Revenue ($)", format="compact"),
        "turnover": st.column_config.NumberColumn("Turnover (x/yr)", format="%.1f"), "dsi": st.column_config.NumberColumn("DSI (days)", format="%.0f"),
        "weeks_cover": st.column_config.NumberColumn("Weeks of cover", format="%.1f"), "service_level": st.column_config.NumberColumn("Service level", format="percent"),
        "lost_revenue": st.column_config.NumberColumn("Lost revenue ($)", format="compact"), "avg_stock_value": st.column_config.NumberColumn("Avg stock at cost ($)", format="compact")})


def tab_credit(d, h, f, a, b, cred_edit, cred_default):
    st.warning("**Scenario layer - assumptions, not data.** The dataset has no customers, invoices or payment terms, so DSO and the default-risk rating are driven by the "
               "assumptions below (edit them to see the effect). Revenue, margin and concentration come from the data.")
    st.markdown("##### Credit assumptions by category (editable)")
    edited = st.data_editor(cred_edit, key="credit_editor", hide_index=True, width="stretch", num_rows="fixed", column_config={
        "category": st.column_config.TextColumn("Category", disabled=True), "terms_days": st.column_config.NumberColumn("Payment terms (days)", min_value=0, max_value=180, step=5),
        "credit_share_pct": st.column_config.NumberColumn("Share of sales on credit (%)", min_value=0, max_value=100, step=5),
        "avg_delay_days": st.column_config.NumberColumn("Average payment delay (days)", min_value=0, max_value=90, step=1),
        "annual_default_rate_pct": st.column_config.NumberColumn("Annual default rate on credit sales (%)", min_value=0, max_value=20, step=0.1)})
    if st.button("Reset assumptions to defaults"):
        st.session_state.pop("credit_editor", None)
        st.rerun()
    ct = credit_table(h, a, b, edited)
    dso = float((ct.dso * ct.revenue).sum() / ct.revenue.sum())
    c = st.columns(4)
    c[0].metric("DSO (revenue-weighted)", f"{dso:.0f} days")
    c[1].metric("Receivables outstanding", money(ct.receivables.sum()))
    c[2].metric("Expected credit loss / year", money(ct.ecl_annual.sum()), f"{100 * ct.ecl_annual.sum() / (ct.gross_profit.sum() * WEEKS_PER_YEAR / (b - a + 1)):.1f}% of gross profit", delta_color="off")
    c[3].metric("Categories rated D or E", int(ct.rating.isin(["D", "E"]).sum()))
    c1, c2 = st.columns([3, 2])
    s = ct.sort_values("risk_score")
    fig = go.Figure(go.Bar(y=s.category, x=s.risk_score, orientation="h", marker_color=[RATING_COLOR[r] for r in s.rating], text=[f"{r}  ({v:.0f})" for r, v in zip(s.rating, s.risk_score)],
                           textposition="outside", hovertemplate="score %{x:.0f}"))
    fig.update_xaxes(range=[0, 100], title="risk score (0 = lowest risk)")
    with c1:
        show(style(fig, 360, "Default-risk score and rating by category (scenario)", legend=False), "cr_score")
    wk = h[(h.week_id >= a) & (h.week_id <= b)].groupby(["week_id", "week_start", "category"]).revenue.sum().reset_index()
    wk["rev4"] = wk.groupby("category").revenue.transform(lambda x: x.rolling(4, min_periods=1).mean())
    wk = wk.merge(ct[["category", "dso"]], on="category")
    ar = wk.assign(ar=wk.rev4 / 7 * wk.dso).groupby("week_start").ar.sum().reset_index()
    fig = go.Figure(go.Scatter(x=ar.week_start, y=ar.ar, line=dict(color=BLUE, width=2), fill="tozeroy", fillcolor="rgba(42,120,214,0.12)", hovertemplate="%{y:$,.0f}"))
    fig.update_yaxes(tickprefix="$", tickformat="~s")
    with c2:
        show(style(fig, 360, "Receivables over time (scenario)", legend=False), "cr_ar")
    st.markdown("##### Scoring table")
    t = ct[["category", "revenue", "rev_share", "dso", "receivables", "ecl_annual", "ecl_pct_gp", "s_default", "s_late", "s_buffer", "s_conc", "risk_score", "rating"]].sort_values("risk_score", ascending=False)
    st.dataframe(t, hide_index=True, width="stretch", column_config={
        "category": "Category", "revenue": st.column_config.NumberColumn("Revenue ($)", format="compact"), "rev_share": st.column_config.NumberColumn("Share of revenue", format="percent"),
        "dso": st.column_config.NumberColumn("DSO (days)", format="%.0f"), "receivables": st.column_config.NumberColumn("Receivables ($)", format="compact"),
        "ecl_annual": st.column_config.NumberColumn("Expected loss / yr ($)", format="compact"), "ecl_pct_gp": st.column_config.NumberColumn("Loss % of GP", format="percent"),
        "s_default": st.column_config.NumberColumn("Default pts", format="%.0f"), "s_late": st.column_config.NumberColumn("Lateness pts", format="%.0f"),
        "s_buffer": st.column_config.NumberColumn("Loss-vs-margin pts", format="%.0f"), "s_conc": st.column_config.NumberColumn("Concentration pts", format="%.0f"),
        "risk_score": st.column_config.NumberColumn("Risk score", format="%.0f"), "rating": "Rating"})
    st.caption("Risk score = 40% default rate (3% = max) + 20% lateness (delay/terms, 50% = max) + 25% expected loss vs gross profit (15% = max) + 15% revenue concentration (25% share = max). "
               "Ratings: A < 20, B < 35, C < 50, D < 65, E >= 65. Illustrative scoring model - calibrate with real customer data.")
    return edited


def forecast_scope(d, h, f, key="fc"):
    c = st.columns([1, 2])
    level = c[0].radio("Scope", ["Company", "Category", "Product"], horizontal=True, key=f"{key}_level")
    if level == "Category":
        sel = c[1].selectbox("Category", sorted(d["products"].category.unique()), key=f"{key}_cat")
        return level, sel, d["hist"][d["hist"].category == sel], d["fcst"][d["fcst"].category == sel]
    if level == "Product":
        sel = c[1].selectbox("Product", sorted(d["products"].product_name.unique()), key=f"{key}_prod")
        return level, sel, d["hist"][d["hist"].product_name == sel], d["fcst"][d["fcst"].product_name == sel]
    return level, "All products", d["hist"], d["fcst"]


def forecast_chart(hh, ff, title, key, weeks_back=104):
    last = hh.week_id.max()
    dh = hh[hh.week_id > last - weeks_back].groupby(["week_id", "week_start"]).agg(sales=("units", "sum"), dem=("demand_est", "sum")).reset_index()
    fw = ff.groupby(["week_id", "week_start"]).agg(p50=("demand_forecast", "sum"), p10=("p10", "sum"), p90=("p90", "sum")).reset_index()
    fig = go.Figure()
    fig.add_scatter(x=dh.week_start, y=dh.sales, name="Observed sales", line=dict(color=BLUE, width=2), hovertemplate="%{y:,.0f}")
    fig.add_scatter(x=dh.week_start, y=dh.dem, name="Reconstructed demand", line=dict(color=ORANGE, width=2), hovertemplate="%{y:,.0f}")
    fig.add_scatter(x=fw.week_start, y=fw.p90, line=dict(width=0), showlegend=False, hoverinfo="skip")
    fig.add_scatter(x=fw.week_start, y=fw.p10, line=dict(width=0), fill="tonexty", fillcolor="rgba(27,175,122,0.22)", name="P10-P90 band", hoverinfo="skip")
    fig.add_scatter(x=fw.week_start, y=fw.p50, name="Forecast demand (P50)", line=dict(color=AQUA, width=2.5), hovertemplate="%{y:,.0f}")
    fig.update_yaxes(tickformat="~s", rangemode="tozero")
    show(style(fig, 400, title), key)


def tab_forecast(d, h, f):
    meta = d["meta"]
    level, sel, hh, ff = forecast_scope(d, h, f)
    forecast_chart(hh, ff, f"{sel}: weekly demand forecast for the next {meta['horizon_weeks']} weeks (weeks 261-286)", "fc_chart")
    q = ff.groupby("pq").agg(weeks=("week_id", "nunique"), demand=("demand_forecast", "sum"), p10=("p10", "sum"), p90=("p90", "sum"), potential=("exp_revenue", "sum"),
                             served=("exp_sales_revenue", "sum"), lost=("exp_lost_revenue", "sum"), gp=("exp_gp", "sum")).reset_index()
    pr = ff.groupby("pq").apply(lambda g: np.average(g.prob_stock_below, weights=g.demand_forecast)).rename("prob").reset_index()
    q = q.merge(pr, on="pq")
    c = st.columns(4)
    c[0].metric("Forecast demand (26 weeks)", f"{q.demand.sum():,.0f} units", help="Sum of weekly P50 forecasts.")
    c[1].metric("Revenue potential", money(q.potential.sum()), help="Demand x last-13-week price, if stock never limits sales.")
    c[2].metric("Expected revenue at historical stock", money(q.served.sum()), help="Each product's own last-104-week stock-availability history, simulated.")
    c[3].metric("At risk from stock limits", money(q.lost.sum()), pct(q.lost.sum() / q.potential.sum()) + " of potential", delta_color="off")
    st.markdown("##### By 13-week quarter")
    st.dataframe(q, hide_index=True, width="stretch", column_config={
        "pq": "Quarter (Y6 = forecast year)", "weeks": "Weeks", "demand": st.column_config.NumberColumn("Demand P50 (units)", format="%.0f"),
        "p10": st.column_config.NumberColumn("Sum of weekly P10", format="%.0f"), "p90": st.column_config.NumberColumn("Sum of weekly P90", format="%.0f"),
        "potential": st.column_config.NumberColumn("Revenue potential ($)", format="compact"), "served": st.column_config.NumberColumn("Revenue at historical stock ($)", format="compact"),
        "lost": st.column_config.NumberColumn("Revenue at risk ($)", format="compact"), "gp": st.column_config.NumberColumn("Gross profit potential ($)", format="compact"),
        "prob": st.column_config.NumberColumn("Prob. stock < demand", format="percent")})
    w = ff.groupby(["week_id", "week_start"]).agg(p50=("demand_forecast", "sum"), p10=("p10", "sum"), p90=("p90", "sum"), potential=("exp_revenue", "sum"),
                                                  served=("exp_sales_revenue", "sum"), lost=("exp_lost_revenue", "sum")).reset_index()
    st.download_button("Download weekly forecast (CSV)", w.to_csv(index=False).encode(), file_name=f"forecast_{sel.replace(' ', '_')}_{VERSION}.csv", mime="text/csv")
    st.info(f"**Model:** {meta['selected_model']} - selected from {meta['n_models']} models by rolling-origin backtests. Accuracy (WAPE): {100 * float(meta['wape']):.1f}% on reconstructed demand, "
            f"**{100 * float(meta['wape_truth']):.1f}% on weeks where demand was directly observed** (the honest figure). Bands: P10-P90 from backtest errors (80% coverage).")


def tab_drill(d, h, cred, a, b, thr, al):
    st.caption("Three-level drill-down: **Level 1** company by category -> **Level 2** products in a category -> **Level 3** a single product.")
    hh = d["hist"]
    rows = []
    ct_all = credit_table(hh, a, b, cred).set_index("category")             # shares and ratings are company-wide
    for cat, hc in hh.groupby("category"):
        kk = kpis(hc, a, b)
        rows.append(dict(category=cat, products=hc.product_id.nunique(), revenue=kk["revenue"], growth=growth_yoy(hc, a, b), gpm=kk["gpm"], turnover=kk["turnover"], weeks_cover=kk["weeks_cover"],
                         service_level=kk["service_level"], lost_revenue=kk["lost_revenue"], dso=float(ct_all.loc[cat, "dso"]), rating=ct_all.loc[cat, "rating"]))
    st.markdown("**Level 1 - categories** (company total: " + money(sum(r["revenue"] for r in rows)) + ")")
    st.dataframe(pd.DataFrame(rows).sort_values("revenue", ascending=False), hide_index=True, width="stretch", column_config={
        "category": "Category", "products": "Products", "revenue": st.column_config.NumberColumn("Revenue ($)", format="compact"), "growth": st.column_config.NumberColumn("Growth vs LY", format="percent"),
        "gpm": st.column_config.NumberColumn("Gross margin", format="percent"), "turnover": st.column_config.NumberColumn("Turnover", format="%.1f"),
        "weeks_cover": st.column_config.NumberColumn("Weeks of cover", format="%.1f"), "service_level": st.column_config.NumberColumn("Service level", format="percent"),
        "lost_revenue": st.column_config.NumberColumn("Lost revenue ($)", format="compact"), "dso": st.column_config.NumberColumn("DSO (scenario)", format="%.0f"), "rating": "Risk (scenario)"})
    cats = sorted(hh.category.unique())
    cat = st.selectbox("Level 2 - choose a category", cats, key="dd_cat")
    hc = hh[hh.category == cat]
    prow = []
    for pid, hp in hc.groupby("product_id"):
        kk = kpis(hp, a, b)
        prow.append(dict(product=hp.product_name.iloc[0], segment=hp.segment.iloc[0], revenue=kk["revenue"], growth=growth_yoy(hp, a, b), gpm=kk["gpm"], opm=kk["opm"],
                         turnover=kk["turnover"], dsi=kk["dsi"], weeks_cover=kk["weeks_cover"], service_level=kk["service_level"], lost_revenue=kk["lost_revenue"]))
    st.markdown(f"**Level 2 - products in {cat}**")
    st.dataframe(pd.DataFrame(prow).sort_values("revenue", ascending=False), hide_index=True, width="stretch", column_config={
        "product": "Product", "segment": "Segment", "revenue": st.column_config.NumberColumn("Revenue ($)", format="compact"), "growth": st.column_config.NumberColumn("Growth vs LY", format="percent"),
        "gpm": st.column_config.NumberColumn("Gross margin", format="percent"), "opm": st.column_config.NumberColumn("Operating margin", format="percent"),
        "turnover": st.column_config.NumberColumn("Turnover", format="%.1f"), "dsi": st.column_config.NumberColumn("DSI (days)", format="%.0f"),
        "weeks_cover": st.column_config.NumberColumn("Weeks of cover", format="%.1f"), "service_level": st.column_config.NumberColumn("Service level", format="percent"),
        "lost_revenue": st.column_config.NumberColumn("Lost revenue ($)", format="compact")})
    prod = st.selectbox("Level 3 - choose a product", sorted(hc.product_name.unique()), key="dd_prod")
    hp, fp = hh[hh.product_name == prod], d["fcst"][d["fcst"].product_name == prod]
    kk = kpis(hp, a, b)
    st.markdown(f"**Level 3 - {prod}**  ({hp.segment.iloc[0]} | {hp.category.iloc[0]})")
    c = st.columns(5)
    c[0].metric("Revenue", money(kk["revenue"])); c[1].metric("Gross margin", pct(kk["gpm"])); c[2].metric("Weeks of cover", num(kk["weeks_cover"], 1))
    c[3].metric("Service level", pct(kk["service_level"])); c[4].metric("Lost revenue", money(kk["lost_revenue"]))
    c1, c2 = st.columns(2)
    last = hp.week_id.max()
    z = hp[hp.week_id > last - 104]
    fig = go.Figure()
    fig.add_scatter(x=z.week_start, y=z.stock_units, name="Stock available", line=dict(color=AQUA, width=2, shape="hv"), hovertemplate="%{y:,.0f}")
    fig.add_scatter(x=z.week_start, y=z.units, name="Observed sales", line=dict(color=BLUE, width=2), hovertemplate="%{y:,.0f}")
    fig.add_scatter(x=z.week_start, y=z.demand_est, name="Reconstructed demand", line=dict(color=ORANGE, width=2), hovertemplate="%{y:,.0f}")
    fig.update_yaxes(tickformat="~s", rangemode="tozero")
    with c1:
        show(style(fig, 380, "Stock available vs sales vs demand (last 104 weeks)"), "dd_stock")
    with c2:
        forecast_chart(hp, fp, "26-week demand forecast with P10-P90", "dd_fc")
    st.markdown("**Alerts for this product**")
    alerts_table(al[al.name == prod], key="dd_alerts")


def tab_alerts(al):
    c = st.columns(4)
    for col, sev in zip(c[:3], ["High", "Medium", "Low"]):
        col.markdown(f"{sev_html(sev)}<br><span style='font-size:30px;font-weight:600'>{int((al.severity == sev).sum())}</span>", unsafe_allow_html=True)
    c[3].metric("$ at stake (all alerts)", money(al.at_stake.sum()), help="Revenue at risk, capital tied up and expected credit loss added together - read by alert type, not as one total.")
    if al.empty:
        alerts_table(al)
        return
    ftype = st.multiselect("Filter by alert type", sorted(al.type.unique()), default=sorted(al.type.unique()), key="al_type")
    t = al[al.type.isin(ftype)]
    alerts_table(t, key="al_table")
    st.download_button("Download alerts (CSV)", t.to_csv(index=False).encode(), file_name=f"alerts_{VERSION}.csv", mime="text/csv")
    s = al.groupby("type").agg(count=("name", "size"), at_stake=("at_stake", "sum")).reset_index().sort_values("at_stake")
    fig = go.Figure(go.Bar(y=s.type, x=s.at_stake, orientation="h", marker_color=BLUE, text=[money(v) for v in s.at_stake], textposition="outside", hovertemplate="%{x:$,.0f}"))
    fig.update_xaxes(tickprefix="$", tickformat="~s")
    show(style(fig, 280, "$ at stake by alert type (different bases: see table)", legend=False), "al_bar")


def tab_about(d):
    m = d["meta"]
    st.markdown(f"""
#### Purpose
Commercial KPI dashboard for Armani Middle East Trading: financial, operational and credit KPIs, the 26-week demand forecast and rule-based alerts.
Data: 30 food-commodity products x 260 weeks ({m['first_week_start'][:10]} to {m['last_week_start'][:10]}, **synthetic calendar** - the source only has week numbers 1-260).
Forecast weeks {m['forecast_first_week'][:10]} to {m['forecast_last_week'][:10]}. Currency is not stated in the data and is shown as $.

#### KPI definitions
| KPI | Definition |
|---|---|
| Revenue | units sold x price (ETL-verified: matches the source for 100% of rows) |
| Gross profit margin | gross profit / revenue, from sums |
| Operating profit | as given in the data; opex is not provided, so opex = gross profit - operating profit (implied) |
| Revenue growth | selected weeks vs the same weeks 52 weeks earlier |
| Inventory turnover | annualised COGS / average inventory at cost (stock available during each week) |
| DSI | average inventory at cost / COGS per day |
| Service level | units sold / reconstructed demand |
| Lost revenue | max(demand - sales, 0) x price: demand not served because of stock-outs or stock caps |
| DSO, default risk | **scenario** - driven by editable assumptions (no receivables / customer data exist) |

#### Important data notes
- **Sales are not demand.** Sales never exceed the previous week's inventory, so in 53% of weeks sales are capped by stock. Demand is reconstructed (observed where stock did not bind; company forecast + seasonal model blend elsewhere).
- **Forecast:** {m['selected_model']}, chosen from {m['n_models']} models. WAPE {100 * float(m['wape']):.1f}% (reconstructed demand) / {100 * float(m['wape_truth']):.1f}% (observed-demand weeks). Historically {float(m['hist_demand_unserved_pct']):.0f}% of demand went unserved.
- **Price has no measurable effect on demand** in this data (elasticity ~ 0), so no price-sensitivity KPI is shown.
- Alerts are rule-based; thresholds are in the sidebar. "$ at stake" is revenue at risk, capital tied up or expected credit loss depending on the alert type.
""")


# ----------------------------------------------------------------------------- main
def main() -> None:
    st.set_page_config(page_title="Armani ME Trading - KPI dashboard", layout="wide", page_icon="📊")
    st.markdown("<style>.block-container{padding-top:1.4rem;max-width:1500px} h1{font-size:1.7rem;margin-bottom:0}</style>", unsafe_allow_html=True)
    d = load_data()
    meta, hist = d["meta"], d["hist"]
    last = int(meta["last_week_id"])
    st.title("Commercial KPI dashboard")
    st.caption("Armani Middle East Trading | 30 food commodities | financial, operational and credit KPIs, 26-week forecast and alerts | dates are a synthetic calendar")

    with st.sidebar:
        st.header("Filters")
        period = st.selectbox("Period", ["Last 13 weeks", "Last 26 weeks", "Last 52 weeks", "Last 104 weeks", "Full history (260 weeks)"], index=2, key="period")
        n = {"Last 13 weeks": 13, "Last 26 weeks": 26, "Last 52 weeks": 52, "Last 104 weeks": 104, "Full history (260 weeks)": 260}[period]
        a, b = last - n + 1, last
        segs = st.multiselect("Stock segment", ["normal", "high_stock"], default=["normal", "high_stock"], key="segs",
                              format_func=lambda s: "Normal stock (23 products)" if s == "normal" else "High stock (7 products)")
        with st.expander("Category & product filters"):
            cats = st.multiselect("Category", sorted(d["products"].category.unique()), default=sorted(d["products"].category.unique()), key="cats")
            prods_all = d["products"][d["products"].segment.isin(segs) & d["products"].category.isin(cats)].product_name.sort_values().tolist()
            prods = st.multiselect("Product", prods_all, default=prods_all, key="prods")
        st.caption(f"{len(prods)} of 30 products | weeks {a}-{b} ({hist[hist.week_id == a].week_start.iloc[0]:%d %b %Y} to {hist[hist.week_id == b].week_start.iloc[0]:%d %b %Y})")
        with st.expander("Alert thresholds"):
            thr = {
                "cover_max": st.number_input("Overstock: weeks of cover above", 1.0, 400.0, DEFAULT_THRESHOLDS["cover_max"], 1.0, key="t1"),
                "lost_share_max": st.number_input("Stock-out risk: % of forecast revenue unserved above", 1.0, 100.0, DEFAULT_THRESHOLDS["lost_share_max"], 1.0, key="t2"),
                "rev_decline_pct": st.number_input("Revenue decline vs last year (%) beyond", 1.0, 100.0, DEFAULT_THRESHOLDS["rev_decline_pct"], 1.0, key="t3"),
                "margin_drop_pp": st.number_input("Gross margin drop (pp) above", 0.1, 20.0, DEFAULT_THRESHOLDS["margin_drop_pp"], 0.1, key="t4"),
                "ecl_gp_max": st.number_input("Credit: expected loss % of gross profit above", 0.5, 50.0, DEFAULT_THRESHOLDS["ecl_gp_max"], 0.5, key="t5"),
                "dso_max": st.number_input("Credit: DSO (days) above", 5.0, 180.0, DEFAULT_THRESHOLDS["dso_max"], 5.0, key="t6"),
                "peak_uplift_pct": st.number_input("Seasonal peak: uplift (%) above", 5.0, 200.0, DEFAULT_THRESHOLDS["peak_uplift_pct"], 5.0, key="t7"),
            }
    if not prods:
        st.warning("No product selected - widen the filters in the sidebar.")
        return
    h = hist[hist.product_name.isin(prods)]
    f = d["fcst"][d["fcst"].product_name.isin(prods)]
    label = period

    names = ["Executive summary", "Financial", "Operations & inventory", "Sales & credit (scenario)", "Forecast", "Drill-down", "Alerts", "About"]
    tabs = st.tabs(names)
    with tabs[3]:                                   # the credit tab returns the (possibly edited) assumptions used by the other tabs
        cred_now = tab_credit(d, h, f, a, b, d["credit_defaults"], d["credit_defaults"])
    al = compute_alerts(d, cred_now, thr)
    with tabs[0]:
        tab_exec(d, h, f, cred_now, a, b, label, al)
    with tabs[1]:
        tab_financial(d, h, f, cred_now, a, b, label)
    with tabs[2]:
        tab_ops(d, h, f, cred_now, a, b, label, thr)
    with tabs[4]:
        tab_forecast(d, h, f)
    with tabs[5]:
        tab_drill(d, h, cred_now, a, b, thr, al)
    with tabs[6]:
        tab_alerts(al)
    with tabs[7]:
        tab_about(d)


if __name__ == "__main__":
    main()
